version: '3'
services:
  app:
    container_name: backend_challenge
    restart: always
    build: .
    ports:
      - 3000:3000
    # desde a versão 3 não é necessário usar o links
    # já vem por default
    depends_on:
      - backend_challenge_db
  backend_challenge_db:
    image: postgres:9.5-alpine
    restart: always
    container_name: backend_challenge_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./resources/init.sh:/docker-entrypoint-initdb.d/init.sh
